/*

Mutations alter states of the store,
@see: https://vuex.vuejs.org/en/mutations.html

It´s good practice to store key of each
mutation in a constant, e.g.:

export const ADD_TO_CART = 'ADD_TO_CART'

*/

export const EXPAND_EXPERIMENT_CONTAINER = 'EXPAND_EXPERIMENT_CONTAINER';
export const REDUCE_EXPERIMENT_CONTAINER = 'REDUCE_EXPERIMENT_CONTAINER';

export const ACTIVATE_EXPERIMENT_CONTAINER = 'ACTIVATE_EXPERIMENT_CONTAINER';
export const DEACTIVATE_EXPERIMENT_CONTAINER = 'DEACTIVATE_EXPERIMENT_CONTAINER';

export const CONTENT_CLICKABLE = 'CONTENT_CLLICKABLE';
export const CONTENT_NOT_CLICKABLE = 'CONTENT_NOT_CLICKABLE';

export const CURRENT_TITLE_VISIBLE = 'CURRENT_TITLE_VISIBLE';
export const CURRENT_TITLE_INVISIBLE = 'CURRENT_TITLE_INVISIBLE';

export const FOOTER_VISIBLE = 'FOOTER_VISIBLE';

export const GITHUB_API_STARTED = 'GITHUB_API_STARTED';
export const GITHUB_API_FINISHED = 'GITHUB_API_FINISHED';

export const GITHUB_API_LOADING_ERROR = 'GITHUB_API_LOADING_ERROR';

export const GITHUB_DATA_MAPPING_STARTED = 'GITHUB_DATA_MAPPING_STARTED';
export const GITHUB_DATA_MAPPING_FINISHED = 'GITHUB_DATA_MAPPING_FINISHED';

export const STORE_GITHUB_REPOS = 'STORE_GITHUB_REPOS';
export const STORE_COMMIT = 'STORE_COMMIT';

export const FOCUS_REPO = 'FOCUS_REPO';
export const UNFOCUS_REPO = 'UNFOCUS_REPO';

export const USED_DATA = 'USED_DATA';

export const UPDATE_LEVEL = 'UPDATE_LEVEL';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
